name: Update Image Name

on:
  push:
    branches:
      - main

jobs:
  update-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Install yq
        run: sudo snap install yq

      - name: Update the image name
        run: |
          yq e '.spec.template.spec.containers[0].image = "weather-app:V2.2"' -i ./app/weather-app.yaml

      # - name: Commit changes
      #   run: |
      #     git config --global user.name 'Your Name'
      #     git config --global user.email 'your-email@example.com'
      #     git add ./path/to/deployment.yaml
      #     git commit -m "Update image name to new-image-name:tag"
      #     git push

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: ./app/weather-app.yaml
          message: "increment the patch number after successful build, Build number"
          pathspec_error_handling: exitImmediately #If add fail, the action will stop right away, and the step will fail
